### ISSUE TITLE
Typescript Angular Directive does not compile with Typescript 1.0

### ISSUE THREAD

**Issue by doczoidberg** [ligershark/side-waffle#111]
```
Error	23	Class directive1 declares interface Idirective1 but does not implement it:
	Type 'directive1' is missing property 'directiveId' from type 'Idirective1'.
```

**Comment by RobHudson72** [comment]
Agreed, this is a bug in the template.

Every time I use the template, I have to comment out the "directiveId: string" line in the Interface.

**Comment by kentcooper** [comment]
This can be closed now. Removed the static variables from the interfaces.

**Comment by sayedihashimi** [comment]
Thanks @kentcooper, closing.

Should we get you added as a contributor so you can close as well?

**Comment by kentcooper** [comment]
@sayedihashimi that's fine I just wanted to clear some of these up since they've been open for so long.

**Comment by sayedihashimi** [comment]
@kentcooper invited, welcome to the SideWaffle contributors! 

I appreciate all your help on the Angular TS. I have been looking for someone for a while to help out. I nearly had to remove them. You are the reason they are still there.

**Comment by RobHudson72** [comment]
I bet these templates will become more popular now that it has been announces that Angular 2.0 will be written in Typescript.

@kentcooper , I share @sayedihashimi 's appreciation!  I use these all the time.

**Comment by kentcooper** [comment]
@sayedihashimi Thanks! I'm glad I could help. I use these templates on a daily bases and would have hate to see them disappear. @RobHudson72 I think so as well. I plan on adding some 2.0 templates as well once I've had a chance to play with it more.
